### ISSUE TITLE
cot_shemefile getter and setter

### ISSUE THREAD

**Issue by esclkm** [Cotonti/Cotonti#1416]
https://github.com/Cotonti/Cotonti/blob/master/system/functions.php#L3320

cot_schemefile - we use for getting theme scheme
but also this function can modify user theme

so:
if this function modify theme^ we get header from one theme and body from another

**Comment by Kilandor** [comment]
Actually I don't think this should be removed. If for some reason it can't find the correct file now no fallback exists.

I do think this function might need some improvement because of 
elseif (is_dir("{$cfg['themes_dir']}/{$usr['theme']}/css/")) 
if this folder exists, it doesn't do the second else if check
elseif (is_dir("{$cfg['themes_dir']}/{$usr['theme']}"))

I mean granted if you have a css folder it shouldn't need to, but it would not hurt to handle it so we check both

We simply need to remove these from being if elseif, elseif to being if, if if

If it finds what it needs it returns it and stops anyways.
