### ISSUE TITLE
cot_log() SQL error 22001

### ISSUE THREAD

**Issue by Alex300** [Cotonti/Cotonti#1572]
There can be a SQL error 22001: String data, right truncated: 1406 Data too long for column 'log_text' at row 1
It appears if log text is too long (more than 255 characters). Truncating is required.

**Comment by Kilandor** [comment]
Why dont we just change the field type to allow more data rather than limit it? Having the uri could be important for tracking problems

**Comment by Alex300** [comment]
Are you suggest to use TEXT instead of varchar (255)? I'm not sure that it makes a sence. All critical errors you will see in log files and on your screen. With file name and line number.
Your solution will increase DB size. But is it will be usefull?

**Comment by Kilandor** [comment]
Yes it's only a potential size increase.  Logger doesn't log critical errors anyways only Cotonti triggered ones. It opens up and removes a limitation if say extensions may want to use it.
I mean their is no way to say for sure if it will be useful. We already have cleaner which removes logs every 15 days by default.

I also think since it has been so long or such a rare occurrence for this issue to come up generally the increase would likely have little effect on db size.

**Comment by etrus** [comment]
What about security? If we allow cot_db to log long texts, bad users can use it in own reasons in bad way. If they create 100000000 entities with very long text will the volume became critical?

**Comment by macik** [comment]
It's need to differ «bad users» and «fool users». As for «bad» they can't spoof db. And «fools» are full responsive for own actions.
