### ISSUE TITLE
 Function create_function() is deprecated in PHP >= 7.2

### ISSUE THREAD

**Issue by etrus** [Cotonti/Cotonti#1599]
Deprecated: Function create_function() is deprecated in 
\plugins\bbcode\inc\bbcode.functions.php on line 303
$text = preg_replace_callback('`'.$bbcode['pattern'].'`mis', **create_function**('$input', $phpcode), $text);

**Comment by Roffun** [comment]
It is easy to replace the function with an anonymous one, but the problem is that inside the callback is an executable function, this entails the need to rewrite the entire function. And this is only for 2 callbacks, 1 of which does not work.
I suggest removing the ability to create bb from the admin panel, transfer them to the bbcodes.parser.php file, by analogy with other extensions.

На русском:
Функцию заменить на анонимную несложно, но проблема в том, что внутри каллбека исполняемая функция, это влечет за собой необходимость переписывания всей функции. И это лишь для 2 каллбеков, 1 из которых не работает.
Предлагаю убрать из админки возможность создания бб,  перенести их в файл bbcodes.parser.php, по аналогии с другими расширениями.
