### ISSUE TITLE
Whosonline falls on internal Ipv6 

### ISSUE THREAD

**Issue by macik** [Cotonti/Cotonti#1634]
[Reported by @pibroens ]

I have the following error:
I restored the site on another host with a lower PHP/SQL version and there it works.

Do you have an idea? Can you help me?

**Fatal error**
2019-05-04 10:37
SQL error 22001: String data, right truncated: 1406 Data too long for column 'online_ip' at row 1
```
#0 cot_diefatal(SQL error 22001: String data, right truncated: 1406 Data too long for column 'online_ip' at row 1) called at [/httpd.www/system/database.php:459]
#1 CotDB->insert(cot_online, Array ([online_ip] => 2a03:1811:1d35:0001:402a:2351:c6b6:e27a,[online_name] => v,[online_lastseen] => 1556966231,[online_location] => home,[online_subloc] => ,[online_userid] => -1,[online_shield] => 0,[online_hammer] => 0)) called at [/httpd.www/plugins/whosonline/whosonline.header.main.php:62]
#2 include(/httpd.www/plugins/whosonline/whosonline.header.main.php) called at [/httpd.www/system/header.php:86]
#3 require_once(/httpd.www/system/header.php) called at [/httpd.www/modules/index/index.php:44]
#4 require_once(/httpd.www/modules/index/index.php) called at [/httpd.www/index.php:176]
```

**Comment by macik** [comment]
Related to #1489.

**Comment by macik** [comment]
@pibroens,
as fast workaround try to extend `online_ip` field in `cot_online` table to 45 char length as follows:
```sql
ALTER TABLE `cot_online` CHANGE `online_ip` `online_ip` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';
```

**Comment by aiwass666** [comment]
My hosting company: one.com sent me this email in regards to this:
The issue was with the storage length of "log_ip column" of "cot_logger". It was unable to handle IP V6 addresses due to its storage restriction to VARCHAR(16) for IPV4 only. The validation requests from "Facebook debugger" and "validator.w3.org" were failing since these were using IPv6 requests and the following error was getting encountered:

"Fatal error: SQL error 22001: String data, right truncated: 1406 Data too long for column 'log_ip'"

They have increased the storage length of this column to store IPv6 addresses and now requests from Facebook debugger and validator.w3.org are getting parsed with 200 status code.

**Comment by Alex300** [comment]
https://github.com/Cotonti/Cotonti/commit/ddea3f9fa2fd2ff2f788f6782a68bebe36c85587 фиксит установочные файлы. Это будет работать только для новых установок системы.

1) Нужно еще решить проблему для существующих и сделать патчи, которые обновят данные.
2) Ну и в setup/install.sql L:265 ('revision', '0.9.19-01') заменить на ('revision', '0.9.22') т.к. изменился скрипт развертывания БД ядра.

**Comment by Dayver** [comment]
> 

1. Да по патчам, помню в ближайших коммитах буду. Тикет уже на автомате закрыл...
2. А вот про эту строчку действительно забыл, спасибо.

**Comment by Dayver** [comment]
> P.S и сразу закрыть #1489

Тот тикет пусть уже отдельно будет.
